name: gitartwork from a contribution graph
on: 
  push:
  pull_request:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:  
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jasineri/gitartwork@v1
        with:
           user_name: enes
           text: ENES
      - uses: jasineri/simple-push-action@v1